apiVersion: v1
kind: Pod
metadata:
  name: myredispod
  namespace: kbench-pod-namespace
  labels:
    name: myredisserverclient
spec:
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: kubernetes.io/hostname
#            operator: In
#            values:
#            - w4-hs2-k0705.eng.vmware.com
  containers:
  - image: nginx 
    resources:
#      limits:
#        memory: "12000Mi"
#        cpu: "2000m"
#      requests:
#        cpu: "50m"
#        memory: "4000Mi"
#        ephemeral-storage: "10Gi"
    command: ["/bin/sh","-c"]
    args: 
      - apt-get update;
        apt-get install -y redis-server;
        apt-get install -y git libssl-dev build-essential autoconf automake libpcre3-dev libevent-dev pkg-config zlib1g-dev;
        git clone https://github.com/RedisLabs/memtier_benchmark.git;
        cd memtier_benchmark/;
        autoreconf -ivf;
        ./configure;
        make;
        sleep infinity;
    name: rediscontainer
